### ISSUE TITLE
Failed to create or merge PR

### ISSUE THREAD

**Issue by gkorland** [TG908/fork-sync#1]
I keep getting the following error
```
 Run TG908/fork-sync@v1.0.44s
##[error]Node run failed with exit code 1
Run TG908/fork-sync@v1.0.4
##[error]Failed to create or merge PR unstable<-RedisLabs:unstable:Validation Failed
##[error]Node run failed with exit code 1
```

See: 
https://github.com/RedisLabs/redis/commit/4d1bdf256ce4239eb09a200e6b326d2e61df6f1b/checks

**Comment by TG908** [comment]
The [Octokit documentation](https://octokit.github.io/rest.js/#octokit-routes-pulls) wasn't very clear about the default value of the `maintainer_can_modify` parameter key. After reading [this](https://github.com/octokit/rest.js/issues/490) I found out that it is `true` by default. Which is the reason why you cannot create any pull requests. I am working on a fix right now which will also improve the error logging and the argument names for the action (e.g `destination_branch` will be base and `origin_branch` will be head).

**Comment by TG908** [comment]
I have created a new release (v1.1.0) fixing your issue. Please make sure to update the parameter naming `destination_branch` -> `base` and `origin_branch` -> `head`. Also you should add the `owner` parameter to your config (I think it should be antirez). Without the owner parameter your PR would be: RedisLabs:unstable<-RedisLabs:unstable. Let me know if it works now.
