### ISSUE TITLE
Support sync fast-forward

### ISSUE THREAD

**Issue by williamdes** [TG908/fork-sync#11]

**Comment by williamdes** [comment]
It could be similar to https://github.com/sudo-bot/action-pull-request-merge/blob/63e3b8fbc04081354c7de47a38d8d8edeefe4be0/index.js#L64

**Comment by TG908** [comment]
Seems like something worth implementing 👍

**Comment by williamdes** [comment]
I created https://github.com/sudo-bot/action-fork-sync that seems to be the best solution for my case

I am closing this one, but if you find a magical way to obtain the commit in the history and then fast forward I will be interested ;)
