### ISSUE TITLE
Doesnt work for private to private forks

### ISSUE THREAD

**Issue by almo-ltoeroek** [TG908/fork-sync#8]
I have a private repo in a different github org I am only a collaborator in, forked by my own private repo.

When I attempt to run the workflow I get not all refs are readable error.

```
 request: {
    method: 'POST',
    url: 'https://api.github.com/repos/my-user/my-repo/pulls',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.30.1 Node.js/12.13.1 (Linux 5.0; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"title":"Fork Sync","head":"otherorg:master","base":"master","body":"","merge_method":"rebase","maintainer_can_modify":false}',
    request: { hook: [Function: bound bound register], validate: [Object] }
  },
  errors: [
    {
      resource: 'PullRequest',
      code: 'custom',
      message: 'not all refs are readable'
    }
  ],
```

**Comment by codeinteger6** [comment]
You need to create a new [Personal access token](https://github.com/settings/tokens) with repo rights and add the token as a secret in your private fork. Then you replace `${{ secrets.GITHUB_TOKEN }}` in the workflow file with `${{ secrets.WHATEVER_YOU_NAMED_YOUR_SECRET }}`. After doing this the action works fine for private to private forks.

**Comment by almo-ltoeroek** [comment]
THanks, that would probably work. It is how I managed to get it working with a custom bash script. Feel free to close this issue.
